name: PapadakisArt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43252
title: 'Papadakis Art  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0026'
    - '#0b2a6b'
    - '#e9b95e'
    - '#77091c'
  brandStrength: 0.7420222146902233
  lightness: 0.7576615395955741
  saturation: 0.812349989078939
  rhythmicContrast: 0.8322836763691157
purpose: []
